<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="data:,">
    <title>Webmon | Websites monitoring</title>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
</head>
<body class="homepage">

<div class="overlay"></div>

<div class="auth-line">
    <a href="/auth/signin">Sign In</a>
    <a href="/auth/signup">Sign Up</a>
</div>

<div class="bottom-left-text">
    Some text
</div>

<div class="bottom-center-button">
    <button class="hp-big">Button</button>
</div>

</body>
</html>
